#
# Makefile for modbus_rtu library
#
# Copyright 2024 Phoenix Systems
#
# Author: Mateusz Kobak
#
# %LICENSE%
#


LOCAL_PATH := $(call my-dir)

NAME := libmodbus
SRCS := $(wildcard $(LOCAL_PATH)*.c)

include $(static-lib.mk)
