#
# Makefile for storage library
#
# Copyright 2022 Phoenix Systems
#
# This file is part of Phoenix-RTOS.
#
# %LICENSE%
#


NAME := libstorage
LOCAL_SRCS := storage.c fs.c
LOCAL_HEADERS_DIR := include
include $(static-lib.mk)
