#
# Makefile for storage library
#
# Copyright 2022 Phoenix Systems
#
# This file is part of Phoenix-RTOS.
#
# %LICENSE%
#

NAME := libstorage
LOCAL_SRCS := storage.c
LOCAL_HEADERS := storage.h

include $(static-lib.mk)
