#
# Makefile for ptable library
#
# Copyright 2023 Phoenix Systems
#
# This file is part of Phoenix-RTOS.
#
# %LICENSE%
#

NAME := libptable
LOCAL_SRCS := ptable.c
LOCAL_HEADERS := ptable.h

include $(static-lib.mk)
