#
# Makefile for uuid library
#
# Copyright 2022 Phoenix Systems
# Author: Damian Loewnau
#
# This file is part of Phoenix-RTOS.
#
# %LICENSE%
#

NAME := libuuid

LOCAL_HEADERS_DIR := include

include $(static-lib.mk)
