#
# Makefile for mbr library
#
# Copyright 2024 Phoenix Systems
#
# This file is part of Phoenix-RTOS.
#
# %LICENSE%
#

NAME := libmbr
LOCAL_SRCS := mbr.c
LOCAL_HEADERS := mbr.h

include $(static-lib.mk)
