#
# Makefile for graphics library test
#
# Copyright 2021 Phoenix Systems
# Author: Lukasz Kosinski
#
# This file is part of Phoenix-RTOS.
#
# %LICENSE%
#

NAME := test-libgraph
LOCAL_SRCS := test.c
DEP_LIBS := libgraph libvga libvirtio

include $(binary.mk)
