#
# Makefile for trace library
#
# Copyright 2025 Phoenix Systems
#
# This file is part of Phoenix-RTOS.
#
# %LICENSE%
#

NAME := libtrace
LOCAL_SRCS := trace.c
LOCAL_HEADERS := trace.h

include $(static-lib.mk)
