#
# Makefile for software watchdog library
#
# Copyright 2022 Phoenix Systems
# Author: Aleksander Kaminski
#
# This file is part of Phoenix-RTOS.
#
# %LICENSE%
#

NAME := libswdg
LOCAL_HEADERS := swdg.h
LOCAL_SRCS := swdg.c
include $(static-lib.mk)
