#
# Makefile for algo library
#
# Copyright 2025 Phoenix Systems
# Author: Ziemowit Leszczynski
#
# This file is part of Phoenix-RTOS.
#
# %LICENSE%
#

NAME := libalgo
LOCAL_HEADERS := lf-fifo.h
LOCAL_SRCS :=
include $(static-lib.mk)
