#
# Makefile for log library
#
# Copyright 2026 Phoenix Systems
# Author: Mikolaj Matalowski
#
# This file is part of Phoenix-RTOS.
#
# %LICENSE%
#

NAME := liblog
LOCAL_HEADERS := logger.h
LOCAL_SRCS := logger.c

include $(static-lib.mk)
