#
# Makefile for mtd library
#
# Copyright 2022 Phoenix Systems
#
# This file is part of Phoenix-RTOS.
#
# %LICENSE%
#


NAME := libmtd
DEPS := libstorage
LOCAL_SRCS := mtd.c
LOCAL_HEADERS_DIR := include
include $(static-lib.mk)
