#
# Makefile for graphics library
#
# Copyright 2022 Phoenix Systems
# Author: Malgorzata Wrobel
#
# This file is part of Phoenix-RTOS.
#
# %LICENSE%
#

NAME := libcache
LOCAL_HEADERS := cache.h
LOCAL_SRCS := cache.c
include $(static-lib.mk)
